// packages/react/src/pages/list.tsx
import { ListController } from "core";
import { useInject, useVueRef } from "../../hooks/use-inject";
import { useEffect } from "react";

function useListController() {
  const listController = useInject(ListController);
  return listController;
}

export const List = () => {
  const listController = useListController();
  useEffect(() => {
    listController.load();
  }, []);
  const userList = listController.userList;
  const userName = useVueRef(listController.userName);
  const avatar = useVueRef(listController.avatar);
  const selectIndex = useVueRef(listController.selectIndex);
  return (
    <div>
      <ul>
        {userList.map((userName, key) => (
          <li
            style={{
              listStyle: "none",
              color: selectIndex === key ? "red" : "",
              padding: "4px 0",
            }}
            key={key}
            onClick={() => {
              listController.changeSelectIndex(key);
            }}
          >
            {userName}
          </li>
        ))}
        <span>{userName}</span>
        <div>{Boolean(avatar) && <img src={avatar} />}</div>
      </ul>
    </div>
  );
};

// packages/vue/src/pages/list.vue
<template>
  <div>
    <ul>
      <li
        v-for="(user, key) of userList"
        :style="style(key)"
        @click="() => changeSelectIndex(key)"
      >
        {{ user }}
      </li>
    </ul>
    <div>
      <h1>当前选中的用户</h1>
      <div>
        <span> {{ userName }} </span>
        <div>
          <img v-if="avatar" :src="avatar" />
        </div>
      </div>
    </div>
  </div>
</template>
<script lang="ts" setup>
import { CSSProperties, computed } from "vue";
import { ListController } from "core";
import { useInject } from "../hooks/use-inject";
const listController = useInject(ListController);
listController.load();
const { userList, userName, avatar, changeSelectIndex } = listController;
const style = computed(() => {
  const selectIndex = listController.selectIndex.value;
  return (currentkey: number) => {
    const css: CSSProperties = {
      listStyle: "none",
      padding: "4px 0",
      fontSize: "20px",
    };
    if (selectIndex === currentkey) {
      css.color = "red";
    }
    return css;
  };
});
</script>
